// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(xeton_coreFFI)
import xeton_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_xeton_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_xeton_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureXetonCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol DownloaderProtocol: AnyObject, Sendable {
    
    func getStatus()  -> DownloadStatus
    
    func pause() async 
    
    func start() async 
    
}
open class Downloader: DownloaderProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_xeton_core_fn_clone_downloader(self.handle, $0) }
    }
public convenience init(url: String, outputPath: String, segments: UInt16) {
    let handle =
        try! rustCall() {
    uniffi_xeton_core_fn_constructor_downloader_new(
        FfiConverterString.lower(url),
        FfiConverterString.lower(outputPath),
        FfiConverterUInt16.lower(segments),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_xeton_core_fn_free_downloader(handle, $0) }
    }

    

    
open func getStatus() -> DownloadStatus  {
    return try!  FfiConverterTypeDownloadStatus_lift(try! rustCall() {
    uniffi_xeton_core_fn_method_downloader_get_status(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func pause()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_downloader_pause(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func start()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_downloader_start(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDownloader: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Downloader

    public static func lift(_ handle: UInt64) throws -> Downloader {
        return Downloader(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Downloader) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Downloader {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Downloader, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloader_lift(_ handle: UInt64) throws -> Downloader {
    return try FfiConverterTypeDownloader.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloader_lower(_ value: Downloader) -> UInt64 {
    return FfiConverterTypeDownloader.lower(value)
}






public protocol SyncServiceProtocol: AnyObject, Sendable {
    
    func discoveredDevices() async  -> [PeerDevice]
    
    func pair(peerId: String, pin: String) async 
    
    func pushLink(peerId: String, url: String) async 
    
    func startDiscovery() async 
    
    func stopDiscovery() async 
    
}
open class SyncService: SyncServiceProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_xeton_core_fn_clone_syncservice(self.handle, $0) }
    }
public convenience init(deviceName: String) {
    let handle =
        try! rustCall() {
    uniffi_xeton_core_fn_constructor_syncservice_new(
        FfiConverterString.lower(deviceName),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_xeton_core_fn_free_syncservice(handle, $0) }
    }

    

    
open func discoveredDevices()async  -> [PeerDevice]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_syncservice_discovered_devices(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_xeton_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_xeton_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypePeerDevice.lift,
            errorHandler: nil
            
        )
}
    
open func pair(peerId: String, pin: String)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_syncservice_pair(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(peerId),FfiConverterString.lower(pin)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func pushLink(peerId: String, url: String)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_syncservice_push_link(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(peerId),FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func startDiscovery()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_syncservice_start_discovery(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func stopDiscovery()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_syncservice_stop_discovery(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSyncService: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SyncService

    public static func lift(_ handle: UInt64) throws -> SyncService {
        return SyncService(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SyncService) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SyncService {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SyncService, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncService_lift(_ handle: UInt64) throws -> SyncService {
    return try FfiConverterTypeSyncService.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncService_lower(_ value: SyncService) -> UInt64 {
    return FfiConverterTypeSyncService.lower(value)
}






public protocol XetonEngineProtocol: AnyObject, Sendable {
    
    func addDownload(props: NewDownloadProps) async  -> Int64
    
    func boot() async 
    
    func deleteDownload(id: Int64, removeFile: Bool) async 
    
    func getDownloadList() async  -> [DownloadItem]
    
    func getTorrentMetadata(id: Int64) async  -> TorrentMetadata?
    
    func nextEvent() async  -> ManagerEvent
    
    func pause(id: Int64) async 
    
    func reloadSettings(settings: DownloadSettings) async 
    
    func reset(id: Int64) async 
    
    func resume(id: Int64) async 
    
    func setGlobalSpeedLimit(bytesPerSecond: Int64) async 
    
    func setProxy(proxy: ProxyConfig) async 
    
    func setTorrentFileSelection(id: Int64, selectedIndices: [UInt32]) async 
    
}
open class XetonEngine: XetonEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_xeton_core_fn_clone_xetonengine(self.handle, $0) }
    }
public convenience init(dataDir: String, settings: DownloadSettings) {
    let handle =
        try! rustCall() {
    uniffi_xeton_core_fn_constructor_xetonengine_new(
        FfiConverterString.lower(dataDir),
        FfiConverterTypeDownloadSettings_lower(settings),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_xeton_core_fn_free_xetonengine(handle, $0) }
    }

    

    
open func addDownload(props: NewDownloadProps)async  -> Int64  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_add_download(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeNewDownloadProps_lower(props)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_i64,
            completeFunc: ffi_xeton_core_rust_future_complete_i64,
            freeFunc: ffi_xeton_core_rust_future_free_i64,
            liftFunc: FfiConverterInt64.lift,
            errorHandler: nil
            
        )
}
    
open func boot()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_boot(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func deleteDownload(id: Int64, removeFile: Bool)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_delete_download(
                    self.uniffiCloneHandle(),
                    FfiConverterInt64.lower(id),FfiConverterBool.lower(removeFile)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func getDownloadList()async  -> [DownloadItem]  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_get_download_list(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_xeton_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_xeton_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeDownloadItem.lift,
            errorHandler: nil
            
        )
}
    
open func getTorrentMetadata(id: Int64)async  -> TorrentMetadata?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_get_torrent_metadata(
                    self.uniffiCloneHandle(),
                    FfiConverterInt64.lower(id)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_xeton_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_xeton_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeTorrentMetadata.lift,
            errorHandler: nil
            
        )
}
    
open func nextEvent()async  -> ManagerEvent  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_next_event(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_xeton_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_xeton_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeManagerEvent_lift,
            errorHandler: nil
            
        )
}
    
open func pause(id: Int64)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_pause(
                    self.uniffiCloneHandle(),
                    FfiConverterInt64.lower(id)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func reloadSettings(settings: DownloadSettings)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_reload_settings(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeDownloadSettings_lower(settings)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func reset(id: Int64)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_reset(
                    self.uniffiCloneHandle(),
                    FfiConverterInt64.lower(id)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func resume(id: Int64)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_resume(
                    self.uniffiCloneHandle(),
                    FfiConverterInt64.lower(id)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func setGlobalSpeedLimit(bytesPerSecond: Int64)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_set_global_speed_limit(
                    self.uniffiCloneHandle(),
                    FfiConverterInt64.lower(bytesPerSecond)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func setProxy(proxy: ProxyConfig)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_set_proxy(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeProxyConfig_lower(proxy)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func setTorrentFileSelection(id: Int64, selectedIndices: [UInt32])async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_method_xetonengine_set_torrent_file_selection(
                    self.uniffiCloneHandle(),
                    FfiConverterInt64.lower(id),FfiConverterSequenceUInt32.lower(selectedIndices)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeXetonEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = XetonEngine

    public static func lift(_ handle: UInt64) throws -> XetonEngine {
        return XetonEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: XetonEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> XetonEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: XetonEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeXetonEngine_lift(_ handle: UInt64) throws -> XetonEngine {
    return try FfiConverterTypeXetonEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeXetonEngine_lower(_ value: XetonEngine) -> UInt64 {
    return FfiConverterTypeXetonEngine.lower(value)
}




public struct DownloadItem: Equatable, Hashable {
    public var name: String
    public var folder: String
    public var link: String
    public var contentLength: Int64
    public var status: DownloadStatus
    public var `protocol`: DownloadProtocol
    public var serverEtag: String?
    public var dateAdded: Int64
    public var startTime: Int64?
    public var completeTime: Int64?
    public var preferredConnections: UInt32?
    public var speedLimit: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, folder: String, link: String, contentLength: Int64, status: DownloadStatus, `protocol`: DownloadProtocol, serverEtag: String?, dateAdded: Int64, startTime: Int64?, completeTime: Int64?, preferredConnections: UInt32?, speedLimit: Int64) {
        self.name = name
        self.folder = folder
        self.link = link
        self.contentLength = contentLength
        self.status = status
        self.`protocol` = `protocol`
        self.serverEtag = serverEtag
        self.dateAdded = dateAdded
        self.startTime = startTime
        self.completeTime = completeTime
        self.preferredConnections = preferredConnections
        self.speedLimit = speedLimit
    }

    

    
}

#if compiler(>=6)
extension DownloadItem: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDownloadItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DownloadItem {
        return
            try DownloadItem(
                name: FfiConverterString.read(from: &buf), 
                folder: FfiConverterString.read(from: &buf), 
                link: FfiConverterString.read(from: &buf), 
                contentLength: FfiConverterInt64.read(from: &buf), 
                status: FfiConverterTypeDownloadStatus.read(from: &buf), 
                protocol: FfiConverterTypeDownloadProtocol.read(from: &buf), 
                serverEtag: FfiConverterOptionString.read(from: &buf), 
                dateAdded: FfiConverterInt64.read(from: &buf), 
                startTime: FfiConverterOptionInt64.read(from: &buf), 
                completeTime: FfiConverterOptionInt64.read(from: &buf), 
                preferredConnections: FfiConverterOptionUInt32.read(from: &buf), 
                speedLimit: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: DownloadItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.folder, into: &buf)
        FfiConverterString.write(value.link, into: &buf)
        FfiConverterInt64.write(value.contentLength, into: &buf)
        FfiConverterTypeDownloadStatus.write(value.status, into: &buf)
        FfiConverterTypeDownloadProtocol.write(value.`protocol`, into: &buf)
        FfiConverterOptionString.write(value.serverEtag, into: &buf)
        FfiConverterInt64.write(value.dateAdded, into: &buf)
        FfiConverterOptionInt64.write(value.startTime, into: &buf)
        FfiConverterOptionInt64.write(value.completeTime, into: &buf)
        FfiConverterOptionUInt32.write(value.preferredConnections, into: &buf)
        FfiConverterInt64.write(value.speedLimit, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadItem_lift(_ buf: RustBuffer) throws -> DownloadItem {
    return try FfiConverterTypeDownloadItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadItem_lower(_ value: DownloadItem) -> RustBuffer {
    return FfiConverterTypeDownloadItem.lower(value)
}


public struct DownloadSettings: Equatable, Hashable {
    public var defaultThreadCount: UInt32
    public var dynamicPartCreation: Bool
    public var useServerLastModified: Bool
    public var globalSpeedLimit: Int64
    public var minPartSize: Int64
    public var maxRetryCount: UInt32
    public var appendExtensionToIncomplete: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(defaultThreadCount: UInt32, dynamicPartCreation: Bool, useServerLastModified: Bool, globalSpeedLimit: Int64, minPartSize: Int64, maxRetryCount: UInt32, appendExtensionToIncomplete: Bool) {
        self.defaultThreadCount = defaultThreadCount
        self.dynamicPartCreation = dynamicPartCreation
        self.useServerLastModified = useServerLastModified
        self.globalSpeedLimit = globalSpeedLimit
        self.minPartSize = minPartSize
        self.maxRetryCount = maxRetryCount
        self.appendExtensionToIncomplete = appendExtensionToIncomplete
    }

    

    
}

#if compiler(>=6)
extension DownloadSettings: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDownloadSettings: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DownloadSettings {
        return
            try DownloadSettings(
                defaultThreadCount: FfiConverterUInt32.read(from: &buf), 
                dynamicPartCreation: FfiConverterBool.read(from: &buf), 
                useServerLastModified: FfiConverterBool.read(from: &buf), 
                globalSpeedLimit: FfiConverterInt64.read(from: &buf), 
                minPartSize: FfiConverterInt64.read(from: &buf), 
                maxRetryCount: FfiConverterUInt32.read(from: &buf), 
                appendExtensionToIncomplete: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DownloadSettings, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.defaultThreadCount, into: &buf)
        FfiConverterBool.write(value.dynamicPartCreation, into: &buf)
        FfiConverterBool.write(value.useServerLastModified, into: &buf)
        FfiConverterInt64.write(value.globalSpeedLimit, into: &buf)
        FfiConverterInt64.write(value.minPartSize, into: &buf)
        FfiConverterUInt32.write(value.maxRetryCount, into: &buf)
        FfiConverterBool.write(value.appendExtensionToIncomplete, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadSettings_lift(_ buf: RustBuffer) throws -> DownloadSettings {
    return try FfiConverterTypeDownloadSettings.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadSettings_lower(_ value: DownloadSettings) -> RustBuffer {
    return FfiConverterTypeDownloadSettings.lower(value)
}


public struct ExtractedMedia: Equatable, Hashable {
    public var title: String
    public var streams: [MediaStream]
    public var thumbnail: String?
    public var durationSec: UInt32?
    public var uploader: String?
    public var description: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(title: String, streams: [MediaStream], thumbnail: String?, durationSec: UInt32?, uploader: String?, description: String?) {
        self.title = title
        self.streams = streams
        self.thumbnail = thumbnail
        self.durationSec = durationSec
        self.uploader = uploader
        self.description = description
    }

    

    
}

#if compiler(>=6)
extension ExtractedMedia: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExtractedMedia: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExtractedMedia {
        return
            try ExtractedMedia(
                title: FfiConverterString.read(from: &buf), 
                streams: FfiConverterSequenceTypeMediaStream.read(from: &buf), 
                thumbnail: FfiConverterOptionString.read(from: &buf), 
                durationSec: FfiConverterOptionUInt32.read(from: &buf), 
                uploader: FfiConverterOptionString.read(from: &buf), 
                description: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ExtractedMedia, into buf: inout [UInt8]) {
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterSequenceTypeMediaStream.write(value.streams, into: &buf)
        FfiConverterOptionString.write(value.thumbnail, into: &buf)
        FfiConverterOptionUInt32.write(value.durationSec, into: &buf)
        FfiConverterOptionString.write(value.uploader, into: &buf)
        FfiConverterOptionString.write(value.description, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractedMedia_lift(_ buf: RustBuffer) throws -> ExtractedMedia {
    return try FfiConverterTypeExtractedMedia.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractedMedia_lower(_ value: ExtractedMedia) -> RustBuffer {
    return FfiConverterTypeExtractedMedia.lower(value)
}


public struct MediaStream: Equatable, Hashable {
    public var url: String
    public var formatId: String
    public var streamType: String
    public var container: String?
    public var videoCodec: String?
    public var audioCodec: String?
    public var height: UInt32?
    public var audioBitrate: UInt32?
    public var filesize: Int64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(url: String, formatId: String, streamType: String, container: String?, videoCodec: String?, audioCodec: String?, height: UInt32?, audioBitrate: UInt32?, filesize: Int64?) {
        self.url = url
        self.formatId = formatId
        self.streamType = streamType
        self.container = container
        self.videoCodec = videoCodec
        self.audioCodec = audioCodec
        self.height = height
        self.audioBitrate = audioBitrate
        self.filesize = filesize
    }

    

    
}

#if compiler(>=6)
extension MediaStream: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMediaStream: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MediaStream {
        return
            try MediaStream(
                url: FfiConverterString.read(from: &buf), 
                formatId: FfiConverterString.read(from: &buf), 
                streamType: FfiConverterString.read(from: &buf), 
                container: FfiConverterOptionString.read(from: &buf), 
                videoCodec: FfiConverterOptionString.read(from: &buf), 
                audioCodec: FfiConverterOptionString.read(from: &buf), 
                height: FfiConverterOptionUInt32.read(from: &buf), 
                audioBitrate: FfiConverterOptionUInt32.read(from: &buf), 
                filesize: FfiConverterOptionInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MediaStream, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.formatId, into: &buf)
        FfiConverterString.write(value.streamType, into: &buf)
        FfiConverterOptionString.write(value.container, into: &buf)
        FfiConverterOptionString.write(value.videoCodec, into: &buf)
        FfiConverterOptionString.write(value.audioCodec, into: &buf)
        FfiConverterOptionUInt32.write(value.height, into: &buf)
        FfiConverterOptionUInt32.write(value.audioBitrate, into: &buf)
        FfiConverterOptionInt64.write(value.filesize, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaStream_lift(_ buf: RustBuffer) throws -> MediaStream {
    return try FfiConverterTypeMediaStream.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaStream_lower(_ value: MediaStream) -> RustBuffer {
    return FfiConverterTypeMediaStream.lower(value)
}


public struct NewDownloadProps: Equatable, Hashable {
    public var name: String
    public var folder: String
    public var link: String
    public var `protocol`: DownloadProtocol
    public var preferredConnections: UInt32?
    public var speedLimit: Int64
    public var onDuplicate: DuplicateStrategy

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, folder: String, link: String, `protocol`: DownloadProtocol, preferredConnections: UInt32?, speedLimit: Int64, onDuplicate: DuplicateStrategy) {
        self.name = name
        self.folder = folder
        self.link = link
        self.`protocol` = `protocol`
        self.preferredConnections = preferredConnections
        self.speedLimit = speedLimit
        self.onDuplicate = onDuplicate
    }

    

    
}

#if compiler(>=6)
extension NewDownloadProps: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNewDownloadProps: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NewDownloadProps {
        return
            try NewDownloadProps(
                name: FfiConverterString.read(from: &buf), 
                folder: FfiConverterString.read(from: &buf), 
                link: FfiConverterString.read(from: &buf), 
                protocol: FfiConverterTypeDownloadProtocol.read(from: &buf), 
                preferredConnections: FfiConverterOptionUInt32.read(from: &buf), 
                speedLimit: FfiConverterInt64.read(from: &buf), 
                onDuplicate: FfiConverterTypeDuplicateStrategy.read(from: &buf)
        )
    }

    public static func write(_ value: NewDownloadProps, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.folder, into: &buf)
        FfiConverterString.write(value.link, into: &buf)
        FfiConverterTypeDownloadProtocol.write(value.`protocol`, into: &buf)
        FfiConverterOptionUInt32.write(value.preferredConnections, into: &buf)
        FfiConverterInt64.write(value.speedLimit, into: &buf)
        FfiConverterTypeDuplicateStrategy.write(value.onDuplicate, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNewDownloadProps_lift(_ buf: RustBuffer) throws -> NewDownloadProps {
    return try FfiConverterTypeNewDownloadProps.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNewDownloadProps_lower(_ value: NewDownloadProps) -> RustBuffer {
    return FfiConverterTypeNewDownloadProps.lower(value)
}


public struct PeerDevice: Equatable, Hashable {
    public var id: String
    public var name: String
    public var ip: String
    public var port: UInt16

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, ip: String, port: UInt16) {
        self.id = id
        self.name = name
        self.ip = ip
        self.port = port
    }

    

    
}

#if compiler(>=6)
extension PeerDevice: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePeerDevice: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PeerDevice {
        return
            try PeerDevice(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                ip: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf)
        )
    }

    public static func write(_ value: PeerDevice, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.ip, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePeerDevice_lift(_ buf: RustBuffer) throws -> PeerDevice {
    return try FfiConverterTypePeerDevice.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePeerDevice_lower(_ value: PeerDevice) -> RustBuffer {
    return FfiConverterTypePeerDevice.lower(value)
}


public struct TorrentMetadata: Equatable, Hashable {
    public var name: String
    public var files: [String]
    public var totalBytes: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, files: [String], totalBytes: Int64) {
        self.name = name
        self.files = files
        self.totalBytes = totalBytes
    }

    

    
}

#if compiler(>=6)
extension TorrentMetadata: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTorrentMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TorrentMetadata {
        return
            try TorrentMetadata(
                name: FfiConverterString.read(from: &buf), 
                files: FfiConverterSequenceString.read(from: &buf), 
                totalBytes: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: TorrentMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterSequenceString.write(value.files, into: &buf)
        FfiConverterInt64.write(value.totalBytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTorrentMetadata_lift(_ buf: RustBuffer) throws -> TorrentMetadata {
    return try FfiConverterTypeTorrentMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTorrentMetadata_lower(_ value: TorrentMetadata) -> RustBuffer {
    return FfiConverterTypeTorrentMetadata.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AudioFormat: Equatable, Hashable {
    
    case mp3
    case aac
    case opus
    case flac





}

#if compiler(>=6)
extension AudioFormat: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAudioFormat: FfiConverterRustBuffer {
    typealias SwiftType = AudioFormat

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AudioFormat {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .mp3
        
        case 2: return .aac
        
        case 3: return .opus
        
        case 4: return .flac
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AudioFormat, into buf: inout [UInt8]) {
        switch value {
        
        
        case .mp3:
            writeInt(&buf, Int32(1))
        
        
        case .aac:
            writeInt(&buf, Int32(2))
        
        
        case .opus:
            writeInt(&buf, Int32(3))
        
        
        case .flac:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioFormat_lift(_ buf: RustBuffer) throws -> AudioFormat {
    return try FfiConverterTypeAudioFormat.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAudioFormat_lower(_ value: AudioFormat) -> RustBuffer {
    return FfiConverterTypeAudioFormat.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DownloadProtocol: Equatable, Hashable {
    
    case http
    case hls
    case ftp
    case torrent





}

#if compiler(>=6)
extension DownloadProtocol: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDownloadProtocol: FfiConverterRustBuffer {
    typealias SwiftType = DownloadProtocol

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DownloadProtocol {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .http
        
        case 2: return .hls
        
        case 3: return .ftp
        
        case 4: return .torrent
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DownloadProtocol, into buf: inout [UInt8]) {
        switch value {
        
        
        case .http:
            writeInt(&buf, Int32(1))
        
        
        case .hls:
            writeInt(&buf, Int32(2))
        
        
        case .ftp:
            writeInt(&buf, Int32(3))
        
        
        case .torrent:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadProtocol_lift(_ buf: RustBuffer) throws -> DownloadProtocol {
    return try FfiConverterTypeDownloadProtocol.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadProtocol_lower(_ value: DownloadProtocol) -> RustBuffer {
    return FfiConverterTypeDownloadProtocol.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DownloadStatus: Equatable, Hashable {
    
    case added
    case downloading
    case paused
    case completed
    case error





}

#if compiler(>=6)
extension DownloadStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDownloadStatus: FfiConverterRustBuffer {
    typealias SwiftType = DownloadStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DownloadStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .added
        
        case 2: return .downloading
        
        case 3: return .paused
        
        case 4: return .completed
        
        case 5: return .error
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DownloadStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .added:
            writeInt(&buf, Int32(1))
        
        
        case .downloading:
            writeInt(&buf, Int32(2))
        
        
        case .paused:
            writeInt(&buf, Int32(3))
        
        
        case .completed:
            writeInt(&buf, Int32(4))
        
        
        case .error:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadStatus_lift(_ buf: RustBuffer) throws -> DownloadStatus {
    return try FfiConverterTypeDownloadStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadStatus_lower(_ value: DownloadStatus) -> RustBuffer {
    return FfiConverterTypeDownloadStatus.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DuplicateStrategy: Equatable, Hashable {
    
    case addNumbered
    case override
    case abort





}

#if compiler(>=6)
extension DuplicateStrategy: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDuplicateStrategy: FfiConverterRustBuffer {
    typealias SwiftType = DuplicateStrategy

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DuplicateStrategy {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .addNumbered
        
        case 2: return .override
        
        case 3: return .abort
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DuplicateStrategy, into buf: inout [UInt8]) {
        switch value {
        
        
        case .addNumbered:
            writeInt(&buf, Int32(1))
        
        
        case .override:
            writeInt(&buf, Int32(2))
        
        
        case .abort:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDuplicateStrategy_lift(_ buf: RustBuffer) throws -> DuplicateStrategy {
    return try FfiConverterTypeDuplicateStrategy.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDuplicateStrategy_lower(_ value: DuplicateStrategy) -> RustBuffer {
    return FfiConverterTypeDuplicateStrategy.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum JobStatus: Equatable, Hashable {
    
    case idle
    case resuming
    case downloading
    case preparingFile
    case retrying
    case canceled
    case finished





}

#if compiler(>=6)
extension JobStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJobStatus: FfiConverterRustBuffer {
    typealias SwiftType = JobStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JobStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .idle
        
        case 2: return .resuming
        
        case 3: return .downloading
        
        case 4: return .preparingFile
        
        case 5: return .retrying
        
        case 6: return .canceled
        
        case 7: return .finished
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: JobStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .idle:
            writeInt(&buf, Int32(1))
        
        
        case .resuming:
            writeInt(&buf, Int32(2))
        
        
        case .downloading:
            writeInt(&buf, Int32(3))
        
        
        case .preparingFile:
            writeInt(&buf, Int32(4))
        
        
        case .retrying:
            writeInt(&buf, Int32(5))
        
        
        case .canceled:
            writeInt(&buf, Int32(6))
        
        
        case .finished:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJobStatus_lift(_ buf: RustBuffer) throws -> JobStatus {
    return try FfiConverterTypeJobStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJobStatus_lower(_ value: JobStatus) -> RustBuffer {
    return FfiConverterTypeJobStatus.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ManagerEvent: Equatable, Hashable {
    
    case jobAdded
    case jobStarting
    case jobStarted
    case jobCanceled
    case jobCompleted
    case jobChanged
    case jobRemoved





}

#if compiler(>=6)
extension ManagerEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeManagerEvent: FfiConverterRustBuffer {
    typealias SwiftType = ManagerEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ManagerEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .jobAdded
        
        case 2: return .jobStarting
        
        case 3: return .jobStarted
        
        case 4: return .jobCanceled
        
        case 5: return .jobCompleted
        
        case 6: return .jobChanged
        
        case 7: return .jobRemoved
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ManagerEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case .jobAdded:
            writeInt(&buf, Int32(1))
        
        
        case .jobStarting:
            writeInt(&buf, Int32(2))
        
        
        case .jobStarted:
            writeInt(&buf, Int32(3))
        
        
        case .jobCanceled:
            writeInt(&buf, Int32(4))
        
        
        case .jobCompleted:
            writeInt(&buf, Int32(5))
        
        
        case .jobChanged:
            writeInt(&buf, Int32(6))
        
        
        case .jobRemoved:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeManagerEvent_lift(_ buf: RustBuffer) throws -> ManagerEvent {
    return try FfiConverterTypeManagerEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeManagerEvent_lower(_ value: ManagerEvent) -> RustBuffer {
    return FfiConverterTypeManagerEvent.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ProxyConfig: Equatable, Hashable {
    
    case none
    case http
    case socks5
    case system





}

#if compiler(>=6)
extension ProxyConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProxyConfig: FfiConverterRustBuffer {
    typealias SwiftType = ProxyConfig

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProxyConfig {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .http
        
        case 3: return .socks5
        
        case 4: return .system
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ProxyConfig, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case .http:
            writeInt(&buf, Int32(2))
        
        
        case .socks5:
            writeInt(&buf, Int32(3))
        
        
        case .system:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProxyConfig_lift(_ buf: RustBuffer) throws -> ProxyConfig {
    return try FfiConverterTypeProxyConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProxyConfig_lower(_ value: ProxyConfig) -> RustBuffer {
    return FfiConverterTypeProxyConfig.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeTorrentMetadata: FfiConverterRustBuffer {
    typealias SwiftType = TorrentMetadata?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeTorrentMetadata.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeTorrentMetadata.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDownloadItem: FfiConverterRustBuffer {
    typealias SwiftType = [DownloadItem]

    public static func write(_ value: [DownloadItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDownloadItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DownloadItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [DownloadItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDownloadItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMediaStream: FfiConverterRustBuffer {
    typealias SwiftType = [MediaStream]

    public static func write(_ value: [MediaStream], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMediaStream.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MediaStream] {
        let len: Int32 = try readInt(&buf)
        var seq = [MediaStream]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMediaStream.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePeerDevice: FfiConverterRustBuffer {
    typealias SwiftType = [PeerDevice]

    public static func write(_ value: [PeerDevice], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePeerDevice.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PeerDevice] {
        let len: Int32 = try readInt(&buf)
        var seq = [PeerDevice]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePeerDevice.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureXetonCoreInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func extractAudio(inputPath: String, outputPath: String, format: AudioFormat)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_func_extract_audio(FfiConverterString.lower(inputPath),FfiConverterString.lower(outputPath),FfiConverterTypeAudioFormat_lower(format)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
public func extractMediaInfo(url: String)async  -> ExtractedMedia  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_func_extract_media_info(FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_rust_buffer,
            completeFunc: ffi_xeton_core_rust_future_complete_rust_buffer,
            freeFunc: ffi_xeton_core_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeExtractedMedia_lift,
            errorHandler: nil
            
        )
}
public func mergeVideoAudio(videoPath: String, audioPath: String, outputPath: String)async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_xeton_core_fn_func_merge_video_audio(FfiConverterString.lower(videoPath),FfiConverterString.lower(audioPath),FfiConverterString.lower(outputPath)
                )
            },
            pollFunc: ffi_xeton_core_rust_future_poll_void,
            completeFunc: ffi_xeton_core_rust_future_complete_void,
            freeFunc: ffi_xeton_core_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_xeton_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_xeton_core_checksum_func_extract_audio() != 36202) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_func_extract_media_info() != 53463) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_func_merge_video_audio() != 44669) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_downloader_get_status() != 24374) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_downloader_pause() != 6656) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_downloader_start() != 8428) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_syncservice_discovered_devices() != 53859) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_syncservice_pair() != 58804) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_syncservice_push_link() != 11917) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_syncservice_start_discovery() != 64249) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_syncservice_stop_discovery() != 25412) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_add_download() != 8923) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_boot() != 16135) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_delete_download() != 46627) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_get_download_list() != 21067) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_get_torrent_metadata() != 14263) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_next_event() != 34750) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_pause() != 12204) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_reload_settings() != 42165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_reset() != 45968) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_resume() != 64658) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_set_global_speed_limit() != 65273) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_set_proxy() != 17069) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_method_xetonengine_set_torrent_file_selection() != 2052) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_constructor_downloader_new() != 3809) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_constructor_syncservice_new() != 36823) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_xeton_core_checksum_constructor_xetonengine_new() != 22543) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureXetonCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all